In [2]:
# ===================== SUMMARY =====================
# This code:
# 1. Imports required libraries (NumPy, Pandas, Math)
# 2. Configures Pandas display settings for better readability
# 3. Uploads a CSV file in Google Colab
# 4. Reads the car dataset into a DataFrame
# 5. Defines column (feature) names for the dataset
# 6. Reloads the dataset with proper column headers
# 7. Displays the first 2 rows of the dataset
# ===================================================


# Import necessary libraries for data handling and numerical operations
import numpy as np
import pandas as pd
import math


# Configure pandas display settings:
# - Show floats with 1 decimal place
# - Limit output to 15 rows for readability
pd.options.display.float_format = '{:.1f}'.format
pd.options.display.max_rows = 15


# Upload file manually in Google Colab environment
car_data_csv = '/Users/luisfaria/Desktop/sEngineer/masters_SWEAI/2026-T1/ISY/modules/module_05_ml-in-depth/cars_data.csv'

# Initial read of dataset (without column names)
car_data = pd.read_csv(car_data_csv)


# Define column names based on dataset documentation
feature_names = ['symboling', 'normalized-losses', 'make', 'fuel-type',
        'aspiration', 'num-doors', 'body-style', 'drive-wheels',
        'engine-location', 'wheel-base', 'length', 'width', 'height', 'weight',
        'engine-type', 'num-cylinders', 'engine-size', 'fuel-system', 'bore',
        'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
        'highway-mpg', 'price']


# Reload dataset with proper column names and encoding
car_data = pd.read_csv(
    "cars_data.csv",
    names=feature_names,
    header=None,
    encoding='latin-1'
)


# Display first 2 rows to verify data structure
car_data.head(2)

,symboling,normalized-losses,make,fuel-type,aspiration,num-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500

In [3]:
# ===================== SUMMARY =====================
# This code:
# 1. Randomly shuffles (reorders) the dataset rows
# 2. Helps prevent any ordering bias that could affect model training
# 3. Prints the total number of records in the dataset
# 4. Displays the first 10 rows after shuffling
# ===================================================


# Shuffle the dataset randomly to avoid any ordering bias
#car_data = car_data.reindex(np.random.permutation(car_data.index))
car_data = car_data.sample(frac=1, random_state=42)


# Print total number of instances (rows) in the dataset
print(" Instances of car prices and details loaded:  ", len(car_data))


# Display first 10 rows of the shuffled dataset
car_data.head(10)

 Instances of car prices and details loaded:   205

,symboling,normalized-losses,make,fuel-type,aspiration,num-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
100,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
132,3,150,saab,gas,std,two,hatchback,fwd,front,99.1,...,121,mpfi,3.54,3.07,9.3,110,5250,21,28,11850
68,-1,93,mercedes-benz,diesel,turbo,four,wagon,rwd,front,110.0,...,183,idi,3.58,3.64,21.5,123,4350,22,25,28248
95,1,128,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799
159,0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56,4500,38,47,7788
162,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70,4800,28,34,9258
147,0,89,subaru,gas,std,four,wagon,fwd,front,97.0,...,108,mpfi,3.62,2.64,9.0,94,5200,25,31,10198
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7775

In [4]:
# ===================== SUMMARY =====================
# This code:
# 1. Defines the target variable (label) as 'price'
# 2. Separates numeric features from the dataset
# 3. Identifies categorical features by excluding numeric features and the label
# 4. Verifies the number of numeric and categorical features using assertions
# ===================================================


# Define the target variable (what we want to predict)
LABEL = 'price'


# Select numeric feature columns from the dataset
numeric_feature_names = car_data[['symboling', 'normalized-losses', 'wheel-base',
        'length', 'width', 'height', 'weight', 'engine-size', 'horsepower',
        'peak-rpm', 'city-mpg', 'highway-mpg', 'bore', 'stroke',
         'compression-ratio']].columns.tolist()


# Identify categorical features by removing numeric features and label from all features
categorical_feature_names = list(set(feature_names) - set(numeric_feature_names) - set([LABEL]))


# Print number of numeric features
print(len(numeric_feature_names))


# Validate expected counts of numeric and categorical features
assert len(numeric_feature_names) == 15
assert len(categorical_feature_names) == 10

15

In [5]:
print(" Only the Numeric features are: ")
car_data[numeric_feature_names]

 Only the Numeric features are:

,symboling,normalized-losses,wheel-base,length,width,height,weight,engine-size,horsepower,peak-rpm,city-mpg,highway-mpg,bore,stroke,compression-ratio
15,0,?,103.5,189.0,66.9,55.7,3230,209,182,5400,16,22,3.62,3.39,8.0
9,0,?,99.5,178.2,67.9,52.0,3053,131,160,5500,16,22,3.13,3.40,7.0
100,0,106,97.2,173.4,65.2,54.7,2302,120,97,5200,27,34,3.33,3.47,8.5
132,3,150,99.1,186.6,66.5,56.1,2658,121,110,5250,21,28,3.54,3.07,9.3
68,-1,93,110.0,190.9,70.3,58.7,3750,183,123,4350,22,25,3.58,3.64,21.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,1,231,99.2,178.5,67.9,49.7,3139,181,160,5200,19,25,3.43,3.27,9.0
14,1,?,103.5,189.0,66.9,55.7,3055,164,121,4250,20,25,3.31,3.19,9.0
92,1,122,94.5,165.3,63.8,54.5,1938,97,69,5200,31,37,3.15,3.29,9.4
179,3,197,102.9,183.5,67.7,52.0,3016,171,161,5200,19,24,3.27,3.35,9.3
102,0,108,100.4,184.6,66.5,56.1,3296,181,152,5200,17,22,3.43,3.27,9.0

In [6]:
# Run to inspect categorical features.
print(" Categorical features")
car_data[categorical_feature_names]

 Categorical features

,engine-type,fuel-system,num-cylinders,make,fuel-type,drive-wheels,aspiration,body-style,engine-location,num-doors
15,ohc,mpfi,six,bmw,gas,rwd,std,sedan,front,four
9,ohc,mpfi,five,audi,gas,4wd,turbo,hatchback,front,two
100,ohc,2bbl,four,nissan,gas,fwd,std,sedan,front,four
132,ohc,mpfi,four,saab,gas,fwd,std,hatchback,front,two
68,ohc,idi,five,mercedes-benz,diesel,rwd,turbo,wagon,front,four
...,...,...,...,...,...,...,...,...,...,...
106,ohcv,mpfi,six,nissan,gas,rwd,std,hatchback,front,two
14,ohc,mpfi,six,bmw,gas,rwd,std,sedan,front,four
92,ohc,2bbl,four,nissan,gas,fwd,std,sedan,front,four
179,dohc,mpfi,six,toyota,gas,rwd,std,hatchback,front,two
102,ohcv,mpfi,six,nissan,gas,fwd,std,wagon,front,four

In [7]:
# Convert numeric features and label to numeric type (invalid values become NaN)
for feature_name in numeric_feature_names + [LABEL]:
    car_data[feature_name] = pd.to_numeric(car_data[feature_name], errors='coerce')

# Count missing values in each column
missing_values = car_data.isna().sum()

# Get only columns that have at least one missing value
columns_with_missing = missing_values[missing_values > 0].index.tolist()

# Print the names of columns with missing values
print("Columns with missing values:", columns_with_missing)

# Optionally fill missing values with 0 (commented out for now)
# car_data.fillna(0, inplace=True)

# Store original dataset length before cleaning
original_length = len(car_data)

# Drop 'normalized-losses' column due to excessive missing values
car_data.drop(labels='normalized-losses', axis=1, inplace=True)

# Update numeric features list
numeric_feature_names = list(set(numeric_feature_names) - set(['normalized-losses']))

# Drop all rows that still contain missing values
car_data.dropna(inplace=True)

# Store new dataset length after cleaning
new_length = len(car_data)

# Print summary of rows dropped and final dataset size
print('Dropped {} rows with missing data'.format(original_length - new_length))
print('Remaining rows:', len(car_data))

Columns with missing values: ['normalized-losses', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']
Dropped 10 rows with missing data
Remaining rows: 195

In [8]:
# ===================== SUMMARY =====================
# This code:
# 1. Imports necessary ML libraries for regression, preprocessing, and model evaluation
# 2. Defines input features (numeric columns) and target variable ('price')
# 3. Optionally includes polynomial feature expansion (commented out)
# 4. Splits the dataset into training (80%) and testing (20%) sets
# 5. Initializes four regression models:
#    - LinearRegression (LR)
#    - GradientBoostingRegressor (GBR)
#    - HistGradientBoostingRegressor (HGBR)
#    - RandomForestRegressor (RBR)
# 6. Loops through each model:
#    - Fits the model on training data
#    - Predicts target values on test data
#    - Computes R² score to evaluate model performance
#    - Prints the model name and its R² score
# ===================================================

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import (GradientBoostingRegressor, HistGradientBoostingRegressor, RandomForestRegressor)

# Select numeric features as inputs (X) and 'price' as target (y)
x = car_data[numeric_feature_names]
y = car_data['price']

# Optional polynomial feature expansion (currently commented out)
# poly = PolynomialFeatures()
# x = poly.fit_transform(x)

# Split data into training (80%) and testing (20%) sets
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2
)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize regression models
LR = LinearRegression()
GBR = GradientBoostingRegressor()
HGBR = HistGradientBoostingRegressor()
RBR = RandomForestRegressor()

n_jobs = -1  # Not used here, but could be passed to parallelizable models

# Fit each model, predict on test set, and evaluate R² score
for model in [LR, GBR, HGBR, RBR]:
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    r2 = r2_score(y_test, y_pred)
    print(model, r2)

LinearRegression() 0.8092481629903749
GradientBoostingRegressor() 0.9246232862415626
HistGradientBoostingRegressor() 0.9244162426771534
RandomForestRegressor() 0.9062050622323039

In [ ]:
# ===================== SUMMARY =====================
# This code:
# 1. Imports RandomForestRegressor and R² metric for evaluation
# 2. Performs manual hyperparameter tuning for Random Forest by looping over:
#    - max_depth: [10, 20, 30]
#    - n_estimators (number of trees): [200, 250, 300, 350, 400]
#    - min_samples_leaf (minimum samples per leaf): [1, 2, 4]
# 3. For each combination:
#    - Initializes a RandomForestRegressor with the current hyperparameters
#    - Trains the model on the training set
#    - Predicts target values on the test set
#    - Computes R² score to measure model performance
#    - Prints the hyperparameter combination and corresponding R² score
# ===================================================

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Hyperparameters
for depth in [10, 20, 30]:  # max_depth
    for n in [200, 250, 300, 350, 400]:  # n_estimators
        for leaf in [1, 2, 4]:  # min_samples_leaf

            # Initialize Random Forest with current hyperparameters
            model = RandomForestRegressor(
                n_estimators=n,
                max_depth=depth,
                min_samples_leaf=leaf,
                n_jobs=-1,
                random_state=42
            )

            # Train model on training data
            model.fit(x_train, y_train)

            # Predict on test data
            y_pred = model.predict(x_test)

            # Compute R² score
            r2 = r2_score(y_test, y_pred)

            # Print hyperparameters and model performance
            print(f"n_estimators={n}, max_depth={depth}, min_leaf={leaf}, R2={r2:.4f}")

n_estimators=200, max_depth=10, min_leaf=1, R2=0.9054
n_estimators=200, max_depth=10, min_leaf=2, R2=0.9046
n_estimators=200, max_depth=10, min_leaf=4, R2=0.8842
n_estimators=250, max_depth=10, min_leaf=1, R2=0.9052
n_estimators=250, max_depth=10, min_leaf=2, R2=0.9030
n_estimators=250, max_depth=10, min_leaf=4, R2=0.8841
n_estimators=300, max_depth=10, min_leaf=1, R2=0.9034
n_estimators=300, max_depth=10, min_leaf=2, R2=0.9008
n_estimators=300, max_depth=10, min_leaf=4, R2=0.8844
n_estimators=350, max_depth=10, min_leaf=1, R2=0.9019
n_estimators=350, max_depth=10, min_leaf=2, R2=0.8998
n_estimators=350, max_depth=10, min_leaf=4, R2=0.8844
n_estimators=400, max_depth=10, min_leaf=1, R2=0.9024
n_estimators=400, max_depth=10, min_leaf=2, R2=0.9003
n_estimators=400, max_depth=10, min_leaf=4, R2=0.8842
n_estimators=200, max_depth=20, min_leaf=1, R2=0.9052
n_estimators=200, max_depth=20, min_leaf=2, R2=0.9046
n_estimators=200, max_depth=20, min_leaf=4, R2=0.8842
n_estimators=250, max_depth=20, min_leaf=1, R2=0.9052
n_estimators=250, max_depth=20, min_leaf=2, R2=0.9029
n_estimators=250, max_depth=20, min_leaf=4, R2=0.8841
n_estimators=300, max_depth=20, min_leaf=1, R2=0.9042
n_estimators=300, max_depth=20, min_leaf=2, R2=0.9007
n_estimators=300, max_depth=20, min_leaf=4, R2=0.8844
n_estimators=350, max_depth=20, min_leaf=1, R2=0.9033
n_estimators=350, max_depth=20, min_leaf=2, R2=0.8996
n_estimators=350, max_depth=20, min_leaf=4, R2=0.8844
n_estimators=400, max_depth=20, min_leaf=1, R2=0.9036
n_estimators=400, max_depth=20, min_leaf=2, R2=0.9003
n_estimators=400, max_depth=20, min_leaf=4, R2=0.8842
n_estimators=200, max_depth=30, min_leaf=1, R2=0.9052
n_estimators=200, max_depth=30, min_leaf=2, R2=0.9046
n_estimators=200, max_depth=30, min_leaf=4, R2=0.8842
n_estimators=250, max_depth=30, min_leaf=1, R2=0.9052
n_estimators=250, max_depth=30, min_leaf=2, R2=0.9029
n_estimators=250, max_depth=30, min_leaf=4, R2=0.8841
n_estimators=300, max_depth=30, min_leaf=1, R2=0.9042
n_estimators=300, max_depth=30, min_leaf=2, R2=0.9007
n_estimators=300, max_depth=30, min_leaf=4, R2=0.8844
n_estimators=350, max_depth=30, min_leaf=1, R2=0.9033
n_estimators=350, max_depth=30, min_leaf=2, R2=0.8996
n_estimators=350, max_depth=30, min_leaf=4, R2=0.8844
n_estimators=400, max_depth=30, min_leaf=1, R2=0.9036
n_estimators=400, max_depth=30, min_leaf=2, R2=0.9003
n_estimators=400, max_depth=30, min_leaf=4, R2=0.8842

In [10]:
# ===================== SUMMARY =====================
# This code:
# 1. Performs hyperparameter tuning for RandomForestRegressor by iterating over:
#    - max_depth: [10, 20, 30]
#    - n_estimators: [200, 250, 300, 350, 400]
#    - min_samples_leaf: [1, 2, 4]
# 2. For each combination:
#    - Initializes and trains the Random Forest model
#    - Predicts on the test set
#    - Computes R² score to evaluate model performance
# 3. Keeps track of the best-performing model by:
#    - Comparing current R² score with the best_score so far
#    - Updating best_score and best_params when a better score is found
# 4. Prints the R² score for each combination
# 5. After all iterations, prints the best R² score and corresponding hyperparameters
# ===================================================

best_score = -1
best_params = {}

for depth in [10, 20, 30]:
    for n in [200, 250, 300, 350, 400]:
        for leaf in [1, 2, 4]:

            # Initialize Random Forest with current hyperparameters
            model = RandomForestRegressor(
                n_estimators=n,
                max_depth=depth,
                min_samples_leaf=leaf,
                n_jobs=-1,
                random_state=42
            )

            # Train the model
            model.fit(x_train, y_train)

            # Predict on test data
            y_pred = model.predict(x_test)

            # Compute R² score
            r2 = r2_score(y_test, y_pred)

            # Update best score and parameters if current model is better
            if r2 > best_score:
                best_score = r2
                best_params = {
                    'n_estimators': n,
                    'max_depth': depth,
                    'min_samples_leaf': leaf
                }

            # Print current hyperparameters and R²
            print(f"n={n}, depth={depth}, leaf={leaf}, R2={r2:.4f}")

# Print the best R² score and corresponding hyperparameters
print("\nBest Score:", best_score)
print("Best Params:", best_params)

n=200, depth=10, leaf=1, R2=0.9054
n=200, depth=10, leaf=2, R2=0.9046
n=200, depth=10, leaf=4, R2=0.8842
n=250, depth=10, leaf=1, R2=0.9052
n=250, depth=10, leaf=2, R2=0.9030
n=250, depth=10, leaf=4, R2=0.8841
n=300, depth=10, leaf=1, R2=0.9034
n=300, depth=10, leaf=2, R2=0.9008
n=300, depth=10, leaf=4, R2=0.8844
n=350, depth=10, leaf=1, R2=0.9019
n=350, depth=10, leaf=2, R2=0.8998
n=350, depth=10, leaf=4, R2=0.8844
n=400, depth=10, leaf=1, R2=0.9024
n=400, depth=10, leaf=2, R2=0.9003
n=400, depth=10, leaf=4, R2=0.8842
n=200, depth=20, leaf=1, R2=0.9052
n=200, depth=20, leaf=2, R2=0.9046
n=200, depth=20, leaf=4, R2=0.8842
n=250, depth=20, leaf=1, R2=0.9052
n=250, depth=20, leaf=2, R2=0.9029
n=250, depth=20, leaf=4, R2=0.8841
n=300, depth=20, leaf=1, R2=0.9042
n=300, depth=20, leaf=2, R2=0.9007
n=300, depth=20, leaf=4, R2=0.8844
n=350, depth=20, leaf=1, R2=0.9033
n=350, depth=20, leaf=2, R2=0.8996
n=350, depth=20, leaf=4, R2=0.8844
n=400, depth=20, leaf=1, R2=0.9036
n=400, depth=20, leaf=2, R2=0.9003
n=400, depth=20, leaf=4, R2=0.8842
n=200, depth=30, leaf=1, R2=0.9052
n=200, depth=30, leaf=2, R2=0.9046
n=200, depth=30, leaf=4, R2=0.8842
n=250, depth=30, leaf=1, R2=0.9052
n=250, depth=30, leaf=2, R2=0.9029
n=250, depth=30, leaf=4, R2=0.8841
n=300, depth=30, leaf=1, R2=0.9042
n=300, depth=30, leaf=2, R2=0.9007
n=300, depth=30, leaf=4, R2=0.8844
n=350, depth=30, leaf=1, R2=0.9033
n=350, depth=30, leaf=2, R2=0.8996
n=350, depth=30, leaf=4, R2=0.8844
n=400, depth=30, leaf=1, R2=0.9036
n=400, depth=30, leaf=2, R2=0.9003
n=400, depth=30, leaf=4, R2=0.8842

Best Score: 0.9054381949519872
Best Params: {'n_estimators': 200, 'max_depth': 10, 'min_samples_leaf': 1}

In [11]:
x.head(10)

,weight,stroke,height,length,horsepower,wheel-base,symboling,peak-rpm,city-mpg,compression-ratio,bore,width,highway-mpg,engine-size
15,3230,3.4,55.7,189.0,182.0,103.5,0,5400.0,16,8.0,3.6,66.9,22,209
100,2302,3.5,54.7,173.4,97.0,97.2,0,5200.0,27,8.5,3.3,65.2,34,120
132,2658,3.1,56.1,186.6,110.0,99.1,3,5250.0,21,9.3,3.5,66.5,28,121
68,3750,3.6,58.7,190.9,123.0,110.0,-1,4350.0,22,21.5,3.6,70.3,25,183
95,2028,3.3,53.3,165.6,69.0,94.5,1,5200.0,31,9.4,3.1,63.8,37,97
159,2275,3.4,52.8,166.3,56.0,95.7,0,4500.0,38,22.5,3.3,64.4,47,110
162,2140,3.0,52.8,166.3,70.0,95.7,0,4800.0,28,9.0,3.2,64.4,34,98
147,2455,2.6,53.0,173.5,94.0,97.0,0,5200.0,25,9.0,3.6,65.4,31,108
182,2261,3.4,55.7,171.7,52.0,97.3,2,4800.0,37,23.0,3.0,65.5,46,97
191,2661,3.4,55.1,180.2,110.0,100.4,0,5500.0,19,8.5,3.2,66.9,24,136

In [12]:
# ===================== SUMMARY =====================
# This code:
# 1. Imports MinMaxScaler from sklearn for feature normalization
# 2. Initializes the scaler object
# 3. Applies Min-Max scaling to input features (x) so that all values are in the range [0, 1]
# 4. Converts the scaled array back to a Pandas DataFrame with original column names
# 5. Prepares the target variable (y_series) from the 'price' column
# 6. Resets the indices of both x and y_series to ensure alignment after scaling
# 7. Displays the first 10 rows of the normalized input features
# ===================================================

from sklearn.preprocessing import MinMaxScaler

# Instantiate the scaler
scaler = MinMaxScaler()

# Apply the scaler to numeric features
X_normalized = scaler.fit_transform(x)

# Convert scaled array back to DataFrame
x = pd.DataFrame(X_normalized, columns=x.columns)

# Prepare target variable
y_series = car_data['price']

# Reset indices to align X and y
x.reset_index(drop=True, inplace=True)
y_series.reset_index(drop=True, inplace=True)

# Show first 10 rows of normalized features
x.head(10)

,weight,stroke,height,length,horsepower,wheel-base,symboling,peak-rpm,city-mpg,compression-ratio,bore,width,highway-mpg,engine-size
0,0.7,0.6,0.7,0.7,0.6,0.5,0.4,0.5,0.1,0.1,0.8,0.6,0.2,0.6
1,0.3,0.7,0.6,0.5,0.2,0.3,0.4,0.4,0.4,0.1,0.6,0.4,0.5,0.2
2,0.5,0.5,0.7,0.7,0.3,0.4,1.0,0.4,0.2,0.1,0.7,0.5,0.3,0.2
3,0.9,0.7,0.9,0.7,0.4,0.7,0.2,0.1,0.2,0.9,0.7,0.9,0.2,0.5
4,0.2,0.6,0.5,0.4,0.1,0.2,0.6,0.4,0.5,0.2,0.4,0.3,0.6,0.1
5,0.3,0.6,0.4,0.4,0.0,0.3,0.4,0.1,0.7,1.0,0.5,0.4,0.8,0.2
6,0.3,0.5,0.4,0.4,0.1,0.3,0.4,0.3,0.4,0.1,0.5,0.4,0.5,0.1
7,0.4,0.3,0.4,0.5,0.2,0.3,0.4,0.4,0.3,0.1,0.8,0.4,0.4,0.2
8,0.3,0.6,0.7,0.5,0.0,0.3,0.8,0.3,0.7,1.0,0.3,0.4,0.8,0.1
9,0.5,0.6,0.6,0.6,0.3,0.4,0.4,0.6,0.2,0.1,0.5,0.6,0.2,0.3

In [13]:
# ===================== SUMMARY =====================
# This code:
# 1. Splits the dataset into training (80%) and testing (20%) sets using train_test_split
# 2. Performs manual hyperparameter tuning for RandomForestRegressor by iterating over:
#    - max_depth: [10, 20, 30]
#    - n_estimators: [200, 250, 300, 350, 400]
#    - min_samples_leaf: [1, 2, 4]
# 3. For each combination of hyperparameters:
#    - Initializes and trains the Random Forest model on the training set
#    - Predicts target values on the test set
#    - Calculates R² score to evaluate model performance
#    - Updates best_score and best_params if current R² is higher than previous best
#    - Prints current hyperparameters and corresponding R² score
# 4. After all iterations, prints the best R² score and the hyperparameters that achieved it
# ===================================================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Split features and target into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2
)

best_score = -1
best_params = {}

# Hyperparameter grid search
for depth in [10, 20, 30]:
    for n in [200, 250, 300, 350, 400]:
        for leaf in [1, 2, 4]:

            # Initialize Random Forest with current hyperparameters
            model = RandomForestRegressor(
                n_estimators=n,
                max_depth=depth,
                min_samples_leaf=leaf,
                n_jobs=-1,
                random_state=42
            )

            # Train the model
            model.fit(x_train, y_train)

            # Predict on test data
            y_pred = model.predict(x_test)

            # Compute R² score
            r2 = r2_score(y_test, y_pred)

            # Update best score and parameters if current model is better
            if r2 > best_score:
                best_score = r2
                best_params = {
                    'n_estimators': n,
                    'max_depth': depth,
                    'min_samples_leaf': leaf
                }

            # Print current hyperparameters and R² score
            print(f"n={n}, depth={depth}, leaf={leaf}, R2={r2:.4f}")

# Print the best R² score and corresponding hyperparameters
print("\nBest Score:", best_score)
print("Best Params:", best_params)

n=200, depth=10, leaf=1, R2=0.9126
n=200, depth=10, leaf=2, R2=0.9066
n=200, depth=10, leaf=4, R2=0.8929
n=250, depth=10, leaf=1, R2=0.9120
n=250, depth=10, leaf=2, R2=0.9050
n=250, depth=10, leaf=4, R2=0.8913
n=300, depth=10, leaf=1, R2=0.9125
n=300, depth=10, leaf=2, R2=0.9057
n=300, depth=10, leaf=4, R2=0.8920
n=350, depth=10, leaf=1, R2=0.9127
n=350, depth=10, leaf=2, R2=0.9061
n=350, depth=10, leaf=4, R2=0.8930
n=400, depth=10, leaf=1, R2=0.9129
n=400, depth=10, leaf=2, R2=0.9067
n=400, depth=10, leaf=4, R2=0.8936
n=200, depth=20, leaf=1, R2=0.9115
n=200, depth=20, leaf=2, R2=0.9062
n=200, depth=20, leaf=4, R2=0.8929
n=250, depth=20, leaf=1, R2=0.9112
n=250, depth=20, leaf=2, R2=0.9046
n=250, depth=20, leaf=4, R2=0.8913
n=300, depth=20, leaf=1, R2=0.9105
n=300, depth=20, leaf=2, R2=0.9054
n=300, depth=20, leaf=4, R2=0.8920
n=350, depth=20, leaf=1, R2=0.9117
n=350, depth=20, leaf=2, R2=0.9057
n=350, depth=20, leaf=4, R2=0.8930
n=400, depth=20, leaf=1, R2=0.9124
n=400, depth=20, leaf=2, R2=0.9064
n=400, depth=20, leaf=4, R2=0.8936
n=200, depth=30, leaf=1, R2=0.9115
n=200, depth=30, leaf=2, R2=0.9062
n=200, depth=30, leaf=4, R2=0.8929
n=250, depth=30, leaf=1, R2=0.9112
n=250, depth=30, leaf=2, R2=0.9046
n=250, depth=30, leaf=4, R2=0.8913
n=300, depth=30, leaf=1, R2=0.9105
n=300, depth=30, leaf=2, R2=0.9054
n=300, depth=30, leaf=4, R2=0.8920
n=350, depth=30, leaf=1, R2=0.9117
n=350, depth=30, leaf=2, R2=0.9057
n=350, depth=30, leaf=4, R2=0.8930
n=400, depth=30, leaf=1, R2=0.9124
n=400, depth=30, leaf=2, R2=0.9064
n=400, depth=30, leaf=4, R2=0.8936

Best Score: 0.9128686183284612
Best Params: {'n_estimators': 400, 'max_depth': 10, 'min_samples_leaf': 1}

#### Lets consider categorical variables

In [14]:
x = car_data[categorical_feature_names]
print(x)

    engine-type fuel-system num-cylinders           make fuel-type  \
15          ohc        mpfi           six            bmw       gas
100         ohc        2bbl          four         nissan       gas
132         ohc        mpfi          four           saab       gas
68          ohc         idi          five  mercedes-benz    diesel
95          ohc        2bbl          four         nissan       gas
..          ...         ...           ...            ...       ...
106        ohcv        mpfi           six         nissan       gas
14          ohc        mpfi           six            bmw       gas
92          ohc        2bbl          four         nissan       gas
179        dohc        mpfi           six         toyota       gas
102        ohcv        mpfi           six         nissan       gas

    drive-wheels aspiration body-style engine-location num-doors
15           rwd        std      sedan           front      four
100          fwd        std      sedan           front      four
132          fwd        std  hatchback           front       two
68           rwd      turbo      wagon           front      four
95           fwd        std  hatchback           front       two
..           ...        ...        ...             ...       ...
106          rwd        std  hatchback           front       two
14           rwd        std      sedan           front      four
92           fwd        std      sedan           front      four
179          rwd        std  hatchback           front       two
102          fwd        std      wagon           front      four

[195 rows x 10 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder

# Apply Label Encoding to each column in x_df
label_encoder = LabelEncoder()
x_encoded = x.apply(label_encoder.fit_transform)


x_encoded = x.apply(lambda col: LabelEncoder().fit_transform(col))
y_series = car_data['price']
print(x_encoded)

     engine-type  fuel-system  num-cylinders  make  fuel-type  drive-wheels  \
15             2            4              3     2          1             2
100            2            1              2    12          1             1
132            2            4              2    16          1             1
68             2            2              1     9          0             2
95             2            1              2    12          1             1
..           ...          ...            ...   ...        ...           ...
106            4            4              3    12          1             2
14             2            4              3     2          1             2
92             2            1              2    12          1             1
179            0            4              3    18          1             2
102            4            4              3    12          1             1

     aspiration  body-style  engine-location  num-doors
15            0           3                0          1
100           0           3                0          1
132           0           2                0          2
68            1           4                0          1
95            0           2                0          2
..          ...         ...              ...        ...
106           0           2                0          2
14            0           3                0          1
92            0           3                0          1
179           0           2                0          2
102           0           4                0          1

[195 rows x 10 columns]

In [16]:
x_train, x_test, y_train, y_test = train_test_split(
                                                 x_encoded,
                                                 y_series,
                                                 test_size = 0.2
                                                 )


best_score = -1
best_params = {}

for depth in [10, 20, 30]:
    for n in [200, 250, 300, 350, 400]:
        for leaf in [1, 2, 4]:

            model = RandomForestRegressor(
                n_estimators=n,
                max_depth=depth,
                min_samples_leaf=leaf,
                n_jobs=-1,
                random_state=42
            )

            model.fit(x_train, y_train)
            y_pred = model.predict(x_test)

            r2 = r2_score(y_test, y_pred)

            # ✅ Check if current model is better
            if r2 > best_score:
                best_score = r2
                best_params = {
                    'n_estimators': n,
                    'max_depth': depth,
                    'min_samples_leaf': leaf
                }

            print(f"n={n}, depth={depth}, leaf={leaf}, R2={r2:.4f}")

print("\nBest Score:", best_score)
print("Best Params:", best_params)

n=200, depth=10, leaf=1, R2=0.6341
n=200, depth=10, leaf=2, R2=0.7149
n=200, depth=10, leaf=4, R2=0.7491
n=250, depth=10, leaf=1, R2=0.6433
n=250, depth=10, leaf=2, R2=0.7191
n=250, depth=10, leaf=4, R2=0.7481
n=300, depth=10, leaf=1, R2=0.6521
n=300, depth=10, leaf=2, R2=0.7231
n=300, depth=10, leaf=4, R2=0.7509
n=350, depth=10, leaf=1, R2=0.6501
n=350, depth=10, leaf=2, R2=0.7233
n=350, depth=10, leaf=4, R2=0.7520
n=400, depth=10, leaf=1, R2=0.6485
n=400, depth=10, leaf=2, R2=0.7219
n=400, depth=10, leaf=4, R2=0.7518
n=200, depth=20, leaf=1, R2=0.6360
n=200, depth=20, leaf=2, R2=0.7158
n=200, depth=20, leaf=4, R2=0.7491
n=250, depth=20, leaf=1, R2=0.6422
n=250, depth=20, leaf=2, R2=0.7198
n=250, depth=20, leaf=4, R2=0.7481
n=300, depth=20, leaf=1, R2=0.6515
n=300, depth=20, leaf=2, R2=0.7236
n=300, depth=20, leaf=4, R2=0.7509
n=350, depth=20, leaf=1, R2=0.6501
n=350, depth=20, leaf=2, R2=0.7237
n=350, depth=20, leaf=4, R2=0.7520
n=400, depth=20, leaf=1, R2=0.6492
n=400, depth=20, leaf=2, R2=0.7223
n=400, depth=20, leaf=4, R2=0.7518
n=200, depth=30, leaf=1, R2=0.6360
n=200, depth=30, leaf=2, R2=0.7158
n=200, depth=30, leaf=4, R2=0.7491
n=250, depth=30, leaf=1, R2=0.6422
n=250, depth=30, leaf=2, R2=0.7198
n=250, depth=30, leaf=4, R2=0.7481
n=300, depth=30, leaf=1, R2=0.6515
n=300, depth=30, leaf=2, R2=0.7236
n=300, depth=30, leaf=4, R2=0.7509
n=350, depth=30, leaf=1, R2=0.6501
n=350, depth=30, leaf=2, R2=0.7237
n=350, depth=30, leaf=4, R2=0.7520
n=400, depth=30, leaf=1, R2=0.6492
n=400, depth=30, leaf=2, R2=0.7223
n=400, depth=30, leaf=4, R2=0.7518

Best Score: 0.7519978954154756
Best Params: {'n_estimators': 350, 'max_depth': 10, 'min_samples_leaf': 4}

#### Encoded categorical being normalised...