In [37]:
import pandas as pd

In [45]:
df = pd.DataFrame({
    'Job Position': ['CEO', 'CTO', 'Junior Manager', 'Employee'],
    'Years of Experience': [20, 15, 5, None],
    'Salary': [200000, 150000, None, 30000]
})

df

     Job Position  Years of Experience    Salary
0             CEO                 20.0  200000.0
1             CTO                 15.0  150000.0
2  Junior Manager                  5.0       NaN
3        Employee                  NaN   30000.0

In [46]:
# Interpolating missing values in the 'Years of Experience' column
df['Years of Experience'] = df['Years of Experience'].interpolate()
df['Salary'] = df['Salary'].interpolate()

df

     Job Position  Years of Experience    Salary
0             CEO                 20.0  200000.0
1             CTO                 15.0  150000.0
2  Junior Manager                  5.0   90000.0
3        Employee                  5.0   30000.0

## Encoding: One-Hot Encoding on data

In [40]:
df1 = pd.get_dummies(df['Job Position'])
df1

     CEO    CTO  Employee  Junior Manager
0   True  False     False           False
1  False   True     False           False
2  False  False     False            True
3  False  False      True           False

In [44]:
df = pd.concat([df, df1], axis=1).reindex(df.index)
df

,Years of Experience,Salary,CEO,CTO,Employee,Junior Manager,CEO,CTO,Employee,Junior Manager
0,20.0,200000.0,True,False,False,False,True,False,False,False
1,15.0,150000.0,False,True,False,False,False,True,False,False
2,5.0,90000.0,False,False,False,True,False,False,False,True
3,5.0,30000.0,False,False,True,False,False,False,True,False

In [42]:
# Removing the column Job position from df as it is of no use now
df.drop('Job Position', axis=1, inplace=True)
df

   Years of Experience    Salary    CEO    CTO  Employee  Junior Manager
0                 20.0  200000.0   True  False     False           False
1                 15.0  150000.0  False   True     False           False
2                  5.0   90000.0  False  False     False            True
3                  5.0   30000.0  False  False      True           False

## Label Encoding

In [47]:
from sklearn.preprocessing import LabelEncoder

# creating instance
le = LabelEncoder()

# using fit_transform to encode the 'Job Position' column
label = le.fit_transform(df['Job Position'])

# 
label

array([0, 1, 3, 2])

## Churn dataset

In [51]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.ensemble import RandomForestClassifier

data = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 35, 40, 45],
    "MonthlyCharges": [120, 150, 100, 200, 250],
    "ContractType": ["Monthly", "Yearly", "Monthly", "Yearly", "Monthly"],
    "SupportCalls": [2, 0, 1, 3, 4],
    "Churn": [0, 0, 1, 0, 1],
    "PaymentMethod": ["Credit Card", "Bank Transfer", "Credit Card", "Bank Transfer", "Credit Card"],
    "SubscriptionStartDate": ["2020-01-01", "2019-06-15", "2021-03-10", "2018-11-20", "2020-07-05"]
})

data

,CustomerID,Name,Age,MonthlyCharges,ContractType,SupportCalls,Churn,PaymentMethod,SubscriptionStartDate
0,1,Alice,25,120,Monthly,2,0,Credit Card,2020-01-01
1,2,Bob,30,150,Yearly,0,0,Bank Transfer,2019-06-15
2,3,Charlie,35,100,Monthly,1,1,Credit Card,2021-03-10
3,4,David,40,200,Yearly,3,0,Bank Transfer,2018-11-20
4,5,Eve,45,250,Monthly,4,1,Credit Card,2020-07-05

In [52]:
today = pd.to_datetime("2026-03-04")
data["TernureMonths"] = (today - pd.to_datetime(data["SubscriptionStartDate"])).dt.days // 30
data.drop("SubscriptionStartDate", axis=1, inplace=True)
data

,CustomerID,Name,Age,MonthlyCharges,ContractType,SupportCalls,Churn,PaymentMethod,TernureMonths
0,1,Alice,25,120,Monthly,2,0,Credit Card,75
1,2,Bob,30,150,Yearly,0,0,Bank Transfer,81
2,3,Charlie,35,100,Monthly,1,1,Credit Card,60
3,4,David,40,200,Yearly,3,0,Bank Transfer,88
4,5,Eve,45,250,Monthly,4,1,Credit Card,68

In [57]:
# Encoding categorical variables using LabelEncoder
le = LabelEncoder()
data["ContractType"] = le.fit_transform(data["ContractType"])
data["PaymentMethod"] = le.fit_transform(data["PaymentMethod"])

print("Pre Processed Data:")
data

Pre Processed Data:

,CustomerID,Name,Age,MonthlyCharges,ContractType,SupportCalls,Churn,PaymentMethod,TernureMonths
0,1,Alice,25,120,0,2,0,1,75
1,2,Bob,30,150,1,0,0,0,81
2,3,Charlie,35,100,0,1,1,1,60
3,4,David,40,200,1,3,0,0,88
4,5,Eve,45,250,0,4,1,1,68

In [ ]:
# select top4 features
selector = SelectKBest(score_func=chi2, k=4)

X_new = selector.fit_transform(X, y)
selected_features = selector.get_support(indices=True)
print("Selected feature indices:", selected_features)

# Refer to Untitled13.ipynb from classes

NameError: name 'X' is not defined